config/routes.rb
Rails.application.routes.draw do
  resources :food_menus
  resources :foods
  resources :orders
  resources :customers
  resources :dining_tables

end

app/controllers/dining_tables_controller.rb
class DiningTablesController < ApplicationController
  before_action :set_dining_table, only: [:show, :edit, :update, :destroy]

  # GET /dining_tables
  # GET /dining_tables.json
  def index
    @dining_tables = DiningTable.all
  end

  # GET /dining_tables/1
  # GET /dining_tables/1.json
  def show
  end

  # GET /dining_tables/new
  def new
    @dining_table = DiningTable.new
  end

  # GET /dining_tables/1/edit
  def edit
  end

  # POST /dining_tables
  # POST /dining_tables.json
  def create
    @dining_table = DiningTable.new(dining_table_params)

    respond_to do |format|
      if @dining_table.save
        format.html { redirect_to @dining_table, notice: 'Dining table was successfully created.' }
        format.json { render :show, status: :created, location: @dining_table }
      else
        format.html { render :new }
        format.json { render json: @dining_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dining_tables/1
  # PATCH/PUT /dining_tables/1.json
  def update
    respond_to do |format|
      if @dining_table.update(dining_table_params)
        format.html { redirect_to @dining_table, notice: 'Dining table was successfully updated.' }
        format.json { render :show, status: :ok, location: @dining_table }
      else
        format.html { render :edit }
        format.json { render json: @dining_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dining_tables/1
  # DELETE /dining_tables/1.json
  def destroy
    @dining_table.destroy
    respond_to do |format|
      format.html { redirect_to dining_tables_url, notice: 'Dining table was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dining_table
      @dining_table = DiningTable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dining_table_params
      params.require(:dining_table).permit(:customer_id)
    end
end

app/helpers/dining_tables_helper.rb
module DiningTablesHelper
end

app/views/dining_tables/_form.html.erb
<%= form_for(@dining_table) do |f| %>
  <% if @dining_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dining_table.errors.count, "error") %> prohibited this dining_table from being saved:</h2>

      <ul>
      <% @dining_table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dining_tables/edit.html.erb
<h1>Editing Dining Table</h1>

<%= render 'form' %>

<%= link_to 'Show', @dining_table %> |
<%= link_to 'Back', dining_tables_path %>

app/views/dining_tables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dining Tables</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dining_tables.each do |dining_table| %>
      <tr>
        <td><%= dining_table.customer_id %></td>
        <td><%= link_to 'Show', dining_table %></td>
        <td><%= link_to 'Edit', edit_dining_table_path(dining_table) %></td>
        <td><%= link_to 'Destroy', dining_table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dining table', new_dining_table_path %>

app/views/dining_tables/new.html.erb
<h1>New Dining Table</h1>

<%= render 'form' %>

<%= link_to 'Back', dining_tables_path %>

app/views/dining_tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @dining_table.customer_id %>
</p>

<%= link_to 'Edit', edit_dining_table_path(@dining_table) %> |
<%= link_to 'Back', dining_tables_path %>