config/routes.rb
Rails.application.routes.draw do
  resources :food_menus
  resources :foods
  resources :orders
  resources :customers
  resources :dining_tables

end

app/models/food_menu.rb
class FoodMenu < ActiveRecord::Base
  belongs_to :order_id
  belongs_to :food_id
end

app/controllers/food_menus_controller.rb
class FoodMenusController < ApplicationController
  before_action :set_food_menu, only: [:show, :edit, :update, :destroy]

  # GET /food_menus
  # GET /food_menus.json
  def index
    @food_menus = FoodMenu.all
  end

  # GET /food_menus/1
  # GET /food_menus/1.json
  def show
  end

  # GET /food_menus/new
  def new
    @food_menu = FoodMenu.new
  end

  # GET /food_menus/1/edit
  def edit
  end

  # POST /food_menus
  # POST /food_menus.json
  def create
    @food_menu = FoodMenu.new(food_menu_params)

    respond_to do |format|
      if @food_menu.save
        format.html { redirect_to @food_menu, notice: 'Food menu was successfully created.' }
        format.json { render :show, status: :created, location: @food_menu }
      else
        format.html { render :new }
        format.json { render json: @food_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_menus/1
  # PATCH/PUT /food_menus/1.json
  def update
    respond_to do |format|
      if @food_menu.update(food_menu_params)
        format.html { redirect_to @food_menu, notice: 'Food menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_menu }
      else
        format.html { render :edit }
        format.json { render json: @food_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_menus/1
  # DELETE /food_menus/1.json
  def destroy
    @food_menu.destroy
    respond_to do |format|
      format.html { redirect_to food_menus_url, notice: 'Food menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_menu
      @food_menu = FoodMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_menu_params
      params.require(:food_menu).permit(:order_id_id, :food_id_id)
    end
end

app/helpers/food_menus_helper.rb
module FoodMenusHelper
end

app/views/food_menus/_form.html.erb
<%= form_for(@food_menu) do |f| %>
  <% if @food_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_menu.errors.count, "error") %> prohibited this food_menu from being saved:</h2>

      <ul>
      <% @food_menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id_id %><br>
    <%= f.text_field :order_id_id %>
  </div>
  <div class="field">
    <%= f.label :food_id_id %><br>
    <%= f.text_field :food_id_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_menus/edit.html.erb
<h1>Editing Food Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_menu %> |
<%= link_to 'Back', food_menus_path %>

app/views/food_menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Food Menus</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Food</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_menus.each do |food_menu| %>
      <tr>
        <td><%= food_menu.order_id %></td>
        <td><%= food_menu.food_id %></td>
        <td><%= link_to 'Show', food_menu %></td>
        <td><%= link_to 'Edit', edit_food_menu_path(food_menu) %></td>
        <td><%= link_to 'Destroy', food_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food menu', new_food_menu_path %>

app/views/food_menus/new.html.erb
<h1>New Food Menu</h1>

<%= render 'form' %>

<%= link_to 'Back', food_menus_path %>

app/views/food_menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @food_menu.order_id %>
</p>

<p>
  <strong>Food:</strong>
  <%= @food_menu.food_id %>
</p>

<%= link_to 'Edit', edit_food_menu_path(@food_menu) %> |
<%= link_to 'Back', food_menus_path %>