config/routes.rb
Rails.application.routes.draw do
  resources :food_menus
  resources :foods
  resources :orders
  resources :customers
  resources :dining_tables

end

app/models/food.rb
class Food < ActiveRecord::Base
  has_many :food_menus
  has_many :orders, :through => :food_menus

  has_many :images, dependent: :destroy
  accepts_attachments_for :images, attachment: :file, append: true
  attachment :file
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:category, :price, :name, :customize)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% categories = ["Starter", "Main Course", "Dessert"] %>
    <%= f.select :category, categories, :prompt => @food.category %>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :customize %><br>
    <%= f.text_area :customize %>
  </div>
  <div class="field">
    <%= f.label :images_files %><br>
    <%= f.attachment_field :images_files, multiple: true, presigned: true, direct: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Image</th>
      <th>Price</th>
      <th>Description</th>
      <th>Customize</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.category %></td>
        <td><%= attachment_image_tag(product.images.first, :file, :fill, 450, 450) %></td>
        <td><%= food.price %></td>
        <td><%= food.description %></td>
        <td><%= food.customize %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @food.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Customize:</strong>
  <%= @food.customize %>
</p>
<p>
  <strong>Images:</strong>
  <% @product.images.each do |i| %>
    <%= attachment_image_tag(i, :file, :fill, 350, 350, format: "jpg") %>
  <% end %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>